spring:
  profiles: dev,test
  h2:
    console:
      enabled: true
      path: "/h2c"
server:
  port: 10101
---
spring:
  profiles: prod
  h2:
    console:
      enabled: false
---
spring:
  profiles: test
server:
  port: 0